### ISSUE TITLE
can you consider adding pool of connections?

### ISSUE THREAD

**Issue by FuncGuy** [virendradhankar/viredis#1]
Instead of creating the redis connection why can't we create the pool of connections and when the user requests for a connection it will be returned from the pool instead of creating  on dynamic it saves connection creation time.

**Comment by virendradhankar** [comment]
Management of  connections is user's responsibility.  Based on application's requirement, User can maintain a pool of connections or can create a new connection whenever required.

**Comment by FuncGuy** [comment]
We need to provide pool support i think so as they did in the jedis

**Comment by virendradhankar** [comment]
If you want to implement connection pool support, please go ahead. Implement it and raise a PR.

**Comment by FuncGuy** [comment]
Done!!
https://github.com/virendradhankar/viredis/pull/2
